apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dev-assist-frontend
  namespace: default
  labels:
    environment: development
    component: frontend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      labels:
        environment: development
        component: frontend
      annotations:
        # Performance optimizations
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
        # Cost optimization - scale to zero after 15 minutes
        run.googleapis.com/timeout: "300s"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      serviceAccountName: dev-assist-frontend@PROJECT_ID.iam.gserviceaccount.com
      containers:
      - name: frontend
        image: asia-southeast1-docker.pkg.dev/PROJECT_ID/dev-assist/frontend:latest
        ports:
        - name: http1
          containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.25"
            memory: "256Mi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "80"
        # Health check configuration
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
  traffic:
  - percent: 100
    latestRevision: true