apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dev-assist-api
  namespace: default
  labels:
    environment: development
    component: api
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/cpu-throttling: "false"
spec:
  template:
    metadata:
      labels:
        environment: development
        component: api
      annotations:
        # Performance optimizations
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        # Cost optimization - scale to zero after 15 minutes
        run.googleapis.com/timeout: "900s"
        # Security
        run.googleapis.com/vpc-access-connector: projects/PROJECT_ID/locations/REGION/connectors/dev-assist-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      containerConcurrency: 100
      timeoutSeconds: 900
      serviceAccountName: dev-assist-api@PROJECT_ID.iam.gserviceaccount.com
      containers:
      - name: api
        image: asia-southeast1-docker.pkg.dev/PROJECT_ID/dev-assist/api:latest
        ports:
        - name: http1
          containerPort: 8000
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        env:
        - name: APP_DEBUG
          value: "false"
        - name: LOG_LEVEL
          value: "INFO"
        - name: PYTHONPATH
          value: "/app"
        - name: PORT
          value: "8000"
        # Secrets from Cloud Secret Manager
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: development-db-url
              key: latest
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: development-redis-url
              key: latest
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: development-redis-url
              key: latest
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: development-redis-url
              key: latest
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: development-jwt-secret
              key: latest
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: development-openai-api-key
              key: latest
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: development-github-token
              key: latest
        # Health check configuration
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/healthz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        startupProbe:
          httpGet:
            path: /api/v1/ping
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
  traffic:
  - percent: 100
    latestRevision: true